### PR TITLE
remove nmsutils dependency in plugin.yml

### PR DESCRIPTION
**Pull request by RoboMWM**
Unless this is intended?

### CODE REVIEW

**Comment by sanjay900** [comment]
It does depend on nmsutils

**Comment by RoboMWM** [comment]
I thought you said nmsUtils didn't need to be built though? Is it not shaded in the jar?

**Comment by RoboMWM** [comment]
Ok, I guess it isn't... So I do need to build/get a NMSUtils jar

**Comment by sanjay900** [comment]
You going to have to grab the jar for nmsutil-plugin from maven and put it in bukkit, or compile it yourself

**Comment by RoboMWM** [comment]
Oh ok, so I only need to compile the nmsutil-plugin part of the nmsutilsv2 repo. Got it.

**Pull request closed without merging**
